### ISSUE TITLE
Can it work with @angular/common@^4.2.4

### ISSUE THREAD

**Issue by FedC** [mezoistvan/ng2-flatpickr#32]
Currently my Angular setup is running @angular/common@^4.2.4 in order to serve up a server-side angular app with angular Universal.

```
"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/cli": "^1.3.0",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/platform-server": "^4.3.6",
    "@angular/router": "^4.2.4",
    "@nguniversal/express-engine": "^1.0.0-beta.3",
    "@nguniversal/module-map-ngfactory-loader": "^1.0.0-beta.3",
    ...
}
```

When building this project:

```
ERROR in Error: Metadata version mismatch for module ./node_modules/ng2-flatpickr/node_modules/@angular/common/common.d.ts, found version 4, expected 3, resolving symbol Ng2FlatpickrModule in ./node_modules/ng2-flatpickr/ng2-flatpickr.d.ts, resolving symbol Ng2FlatpickrModule in ./node_modules/ng2-flatpickr/ng2-flatpickr.d.ts
```

**Comment by mezoistvan** [comment]
I had no issues working with v4, please doublecheck your versions of the libraries.

**Comment by KristopherWindsor** [comment]
Please reopen. The error happens when compiling AOT for Angular 4.

`Metadata version mismatch for module .../node_modules/ng2-flatpickr/node_modules/@angular/common/common.d.ts, found version 4, expected 3, resolving symbol Ng2FlatpickrModule in .../node_modules/ng2-flatpickr/ng2-flatpickr.d.ts, resolving symbol Ng2FlatpickrModule in .../node_modules/ng2-flatpickr/ng2-flatpickr.d.ts`

ng2-flatpickr ships with ng2-flatpickr.metadata.json that is not compatible with Angular 4. 

<img width="308" alt="screen shot 2018-05-15 at 9 06 41 pm" src="https://user-images.githubusercontent.com/838088/40096124-4b187114-5884-11e8-8bc0-dc3ef64f5d90.png">
