### ISSUE TITLE
formControlName doesn't work.

### ISSUE THREAD

**Issue by adrianoviana** [mezoistvan/ng2-flatpickr#41]
here s my code:

dateOptions: FlatpickrOptions = {
    defaultDate: new Date(),
    locale: Pt.pt,
    dateFormat:'d/m/Y'
  };

myForm = formBuilder.group({
...
      dtaInicio    : [''],
      dtaFim    : [''],
    });
<ng2-flatpickr formControlName="dtaInicio" [config]="dateOptions" ></ng2-flatpickr>

myForm.value.dtaInicio and myForm.value.dtaFim comes always empty!

**Comment by mezoistvan** [comment]
closed due to inactivity

**Comment by ghiscoding** [comment]
I'm having this problem too, basically the issue is that setting the `defaultDate` with the `FlatpickrOptions` shows the value in the input but **does not** update the value in the Reactive Form Control itself. So on top of using the `defaultDate`, I also have to set it with the Reactive Form controls. 

So if we take the example from original question
```typescript
dateOptions: FlatpickrOptions = {
defaultDate: new Date(),
locale: Pt.pt,
dateFormat:'d/m/Y'
};

// doing this extra command does work
myForm = formBuilder.group({
  dtaInicio : [new Date()],  // <<-- SET IT HERE TOO
});
```
That works but it's a little confusing not knowing that the `defaultDate` doesn't work from the get go.
